version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /username
    DOCKER_REGISTRY_PASSWORD: /password
    DOCKER_REGISTRY_URL: /url
phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running tests..."
      - npm install
      - npm run test
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/frontend-kafe:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/frontend-kafe:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'