substitutions:
  _REGION: asia-southeast2
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/containers-repo/app-frontend:$COMMIT_SHA', '.']
  id: build and testing

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/containers-repo/app-frontend:$COMMIT_SHA']
  id: push
  
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: gcloud
  args: 
      [
      "deploy", "releases", "create", "release-$SHORT_SHA",
      "--delivery-pipeline", "pipeline-frontend",
      "--region", "${_REGION}",
      "--images", "app=${_REGION}-docker.pkg.dev/${PROJECT_ID}/containers-repo/app-frontend:$COMMIT_SHA"
      ]

options:
  machineType: 'E2_HIGHCPU_8'