apiVersion: skaffold/v4beta8
kind: Config
metadata: 
  name: frontend
profiles:
- name: staging-frontend
  manifests:
    rawYaml:
    - deploy/staging.yaml
- name: prod-frontend
  manifests:
    rawYaml:
    - deploy/prod.yaml

deploy:
  cloudrun: {}